name: Build Distributable

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
    
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v2

      - name: Check Python Version
        run: python --version

      - name: Check pip Version
        run: pip --version
        
      - name: Install PyInstaller
        run: pip install pyinstaller
        
      - name: Check PyInstaller Version
        run: pyinstaller --version
        
      - name: Create .exe File
        run: pyinstaller --noconsole --onefile --name "phue-racing-flags" gui.py
