name: Build & Release Distributable

on:
  push:
    branches: [ release ]

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v2

      - name: Check Python Version
        run: python --version
      - name: Check pip Version
        run: pip --version
      - name: Install PyInstaller
        run: pip install pyinstaller
      - name: Check PyInstaller Version
        run: pyinstaller --version
      - name: Check npm Version
        run: npm --version
      - name: Install electron via npm
        run: npm install
      - name: Create .exe File
        run: pyinstaller web.py --add-data "eel;eel" --add-data "web;web" --add-data "node_modules/electron/dist;node_modules/electron/dist" --add-data "main.js;node_modules/electron/dist/resources/app" --add-data "package.json;node_modules/electron/dist/resources/app" --add-data="images/icon.ico;node_modules/electron/dist/resources/app"  --onefile --noconsole --name "phue-racing-flags" --icon="images/icon.ico"
      - name: Bump Version and Push Tag
        id: tag_version
        uses: mathieudutour/github-tag-action@v5.5
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: D:\a\phue-racing-flags\phue-racing-flags\dist\phue-racing-flags.exe
          tag_name: ${{ steps.tag_version.outputs.new_tag }}
          release_name: Release ${{ steps.tag_version.outputs.new_tag }}
          body: ${{ steps.tag_version.outputs.changelog }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
